// Code generated by edda-stage-0 (core). DO NOT EDIT.
package main

import (
	"fmt"

	"github.com/JamesPagetButler/qbp-compute-unit/emulator"
)

func main() {
	g := emulator.NewGearbox()
	_ = g
	// contract efimov_triad — cap detector_read @ screen.locale
	v_node0 := [2]float64{1.5, 0.5}
	_ = v_node0
	v_node1 := [2]float64{0.9, -0.1}
	_ = v_node1
	v_node2 := [2]float64{0.4, 0.4}
	_ = v_node2
	v_triad1 := g.CMul64(v_node0, v_node1)
	_ = v_triad1
	v_triad2 := g.CMul64(v_triad1, v_node2)
	_ = v_triad2
	fmt.Println(v_triad2)
}
